### PR TITLE
Prevent duplicate Lycanites Mobs morphs

### PR DESCRIPTION
**Pull request by AshyRaccoon**
"Size" is the main culprit for everything, as well as "Stealth" for Serpix and "Items" for Kobolds.
Heavy-handed, but the rest seem like they may be unnecessary (mostly concerning pets and summons, I think?)
So far, I haven't had a problem acquiring morphs from any of these in single player, and haven't had duplicates anymore.

### CODE REVIEW

**Comment by AshyRaccoon** [comment]
Oops, there, I mistakenly removed Astaroth earlier. The update re-adds that instead of Rahovart. The Rahovart is a boss creature, and I didn't test killing that one, so it's not in the file.

**Comment by iChun** [comment]
Holy, someone actually used this feature! :O 

If you know what class all of those mobs actually extend (eg lycanite.lycanitesmobs.mobs.entity.EntityBase or something like that), you could of actually just put that in and it'll cover all classes that extends that class.

Considering all the tags that you strip are the same, it looks like there's indeed is one generic entity class. I'll let you try and find that out and get back to me before I pull this.

**Comment by AshyRaccoon** [comment]
I was surprised there haven't been more uses of this in all this time!

I was wondering if something like that was possible, a wildcard, or so on, but had no idea what to do or look for. With that example, and poking through the mod some more, I found the base class.
I just gave them all (I think) a run through, killing them, and this seems to work nicely.

**Comment by iChun** [comment]
Ah sorry for the delay. This PR slipped my mind cause I was moving to another state. I'll pull it in now.

**Comment by iChun** [comment]
I'd like to say though do keep in mind Morph 1.10.2+ will use a somewhat different system.

**Comment by AshyRaccoon** [comment]
No problem. I've been distracted lately by some things, too.
No more Lycanite's duplicates (as far as I can tell) for anyone, anywhere, is gonna be pretty nice. I hope it helps out some others out there, who knows. At least I've been playing on a small server, so I know it'll do some good there.
I just kind of got determined, was oddly productive when I had that cold...

I see! When it's out for 1.10.2+, I'll definitely check it out at some point. This has been a fun mod to play with.

**Comment by iChun** [comment]
It'll definitely help loads of peeps. Thanks so much for this PR :)

**Comment by AshyRaccoon** [comment]
Awesome. You're welcome. :)

I think I ended up searching 'duplicate' here, and from there saw the NBT stripper mentioned. That reminded me of NBT Explorer, and I used that to see what Lycanite's morphs had that others didn't. Was very helpful.
It definitely helped mentioning what the Lycanites base class might be named like, too, thank you, I would've had no idea what to look for, otherwise.

**Comment by AshyRaccoon** [comment]
Weird.
I had turned off using local resources again, but I was still getting duplicate morphs until I edited my morph.cfg, changing "S:customPatchLink=" to "S:customPatchLink=https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/", and now it works as expected. It's as if it wasn't using that URL by default.
Same with my server, once I filled that in, no more duplicate morphs happening.

Still, even if that is bugged (?), it was very worth submitting this, it means the file's out there, and learning about using the base class is a big plus, so much cleaner.
It's cool. I just thought I'd post a followup.

**Pull request merged**
