### PR TITLE
Finished porting to 1.12.2

### PR DESCRIPTION
**Pull request by Ajadaz**
I got this beast to work for 1.12.2. I can see that a big overhaul was planned for this mod, but this is just a port from the 1.7.10

### CODE REVIEW

**Comment by alexgurrola** [comment]
@Aidas1000  Wow.  That appears to be everything in terms of the remaining functionality.  I'll be sure to compile this and test it myself later this week.

**Comment by alexgurrola** [comment]
@iChun Looks good!

**Comment by iChun** [comment]
image

Did you..... did you actually... report ALL OF 1.7.10's ABILITIES TO 1.12.2??!?!?!?!?!


image

I'm shocked. I'll have a look see and see what I can do.

**Comment by seymourimadeit** [comment]
holy gucamole my ass is burning

**Comment by Ajadaz** [comment]
Most of the big brain work was already done though, the API was mostly intact and worked, I just needed to tweak a few minor places. After that I just copy pasted the 1.7.10 abilities and adapted them to the changes in 1.12.2. This took less than a week. I think the hardest one to do was the squid ability, because it required to change how the fog worked above and in water.

**Comment by GittyGeneral** [comment]
This sounds promising, I want to check it out but I am having issues with java and cannot compile this into a .jar file to play - can someone please do this and maybe add it to a dropbox for others to download?

**Comment by iChun** [comment]
Now available on [CurseForge in v7.2.0](https://www.curseforge.com/minecraft/mc-mods/morph/files/all). Thanks so much to @Ajadaz for porting it over.

**Comment by CritFlaw** [comment]
Hi, I'm not sure where else to post this, and I don't know if it is caused by the new update, but I'm wondering if there's an issue with adjusting the step height for players. 

In my pack I've disabled all the other options for step-up/auto-jump features and with everlasting abilities, with jump-boost on it does step-up, and without it, I can't even go over half slabs or beds. I got the idea it *could* be Morph from [this](https://www.reddit.com/r/feedthebeast/comments/a062hj/why_cant_i_walk_up_these_chiseled_slabs_i_can/) post which mentions that a mod incorrectly adjusting player step height could do it, so I thought maybe Morph?

Hopefully you can help, thanks!

**Pull request merged**
