### PR TITLE
Ignore NBT from Dye It Yourself

### PR DESCRIPTION
**Pull request by itskieranp**
Should fix iChun/Morph#955 if I worked it out right

### CODE REVIEW

**Comment by iChun** [comment]
Sorry, just seen this now, why 11370?

**Comment by Poke1650** [comment]
Working on fixing this in Dye it yourself directly using IMC

**Comment by Poke1650** [comment]
Fixed in [this commit](https://github.com/Poke1650/Dye-It-Yourself/commit/0b55e1dd2ab636e61217590c0975370a5c8e86d0)

**Comment by Poke1650** [comment]
Ok fixed in the latest released here on [CurseForge](https://minecraft.curseforge.com/projects/dye-it-yourself/files/2567788) (after it's approved)

**Pull request closed without merging**
