### PR TITLE
Update nbt_modifiers with FoolCraft3 / Waffleton creature mods

### PR DESCRIPTION
**Pull request by generrosity**
minecraft:creeper (and others) : hitByDarkSteelSword and ForgeData/ezModsApp, ForgeData/cnpcmarks/marks (I hope I represented that right)
exoticbirds:pigeon (and same mod) : EggLayTime  (sorry I can't figure out the class as it only records entID)
nex:monster_spinout : Spinning, SpinCounter, SpinCooldown (this comes from NetherEx mod - sorry no idea the class name again)
nax:monster_spore: Counter
CustomNpcs:  ... there is tonnes of stuff... is there a way to just block this mod of all tags?
morechickens:[copperchicken]: Analyzed, Gain, Grown, Strength (creates 100s of entities in the nbt - sorry again no idea how to derive the class name)
Misc witherskelly: spawnedByPoweredSpawner
Misc Blaze: CursedEarth

Thank you very much for your consideration - if you can let me know how to retrieve the classnames, I can split the relevant lines out to not affect all creatures.

### CODE REVIEW

**Comment by generrosity** [comment]
Heya @iChun - sorry to be any trouble - is there any way I can make this commit any easier? Sorry, first times adding I think

**Comment by iChun** [comment]
Oh huh I somehow missed this email. Sec lemme have a look.

**Comment by iChun** [comment]
I have to double check but can you try and see if /morph analyse can help you out with the class names?

**Comment by generrosity** [comment]
Thanks for your patience with me @iChun - I've figured out how to split the three creature-specific tags off, and left the tags that Ive found on aaaaall sorts of creatures in.

**Comment by iChun** [comment]
Oh I should have mentioned, please sort the classes alphabetically but leave the Minecraft classes at the bottom of the JSON. Once that's done the PR should be good to pull.

**Comment by generrosity** [comment]
Ah - OK - I think thats in order. Sorry I missed the instruction.

**Comment by generrosity** [comment]
Heya @iChun - how does this look now? Sorry to be a bother

**Comment by iChun** [comment]
Whoops sorry, forgot to check this out again. I'll pull it in now.

**Pull request merged**
