### PR TITLE
Ignore Eclipse muck

### PR DESCRIPTION
**Pull request by queengooborg**

### CODE REVIEW

**Comment by iChun** [comment]
But... I use IDEA...

**Comment by vinyldarkscratch** [comment]
I've never actually played around with IDEA before, I guess that would have to be since I'm familiar with Eclipse.  X3 I'm definitely not the only one either, and others may grab your code and use Eclipse.  Having the ignores for the .gitignore file will make sure that all of the Eclipse project stuff doesn't get staged and committed, letting Gradle take care of it all.  ;)
(This is also because of a little something I'm going to surprise you with.  X3)

**Comment by iChun** [comment]
Well I honestly hope you're not trying to port the mod because I'm planning on rewriting it...

**Comment by vinyldarkscratch** [comment]
That makes sense -- admittedly porting mods to 1.11.2 is what I do in the Minecraft modding community, but my plans are something else.  😛  Alas, I hadn't realized that you planned to rewrite the mod, and as such I'll wait before commencing, so that my changes won't conflict with the new version.  ;)

**Comment by iChun** [comment]
I don't know when that'll be though as I'm fairly busy IRL nowadays. Might
be quite a bit before then. I'll have to see how to goes.

On 6 Apr 2017 5:03 am, "Vinyl Darkscratch" <notifications@github.com> wrote:

That makes sense -- admittedly porting mods to 1.11.2 is what I do in the
Minecraft modding community, but my plans are something else. 😛 Alas, I
hadn't realized that you planned to rewrite the mod, and as such I'll wait
before commencing, so that my changes won't conflict with the new version.
;)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/pull/839#issuecomment-291996029>, or mute
the thread

**Pull request closed without merging**
